/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <SPI0.h>
#include <SPI0_PVT.h>
#include <RED.h>
#include <RED_aliases.h>
#include <BLUE.h>
#include <BLUE_aliases.h>
#include <GREEN.h>
#include <GREEN_aliases.h>
#include <SDCS.h>
#include <SDCS_aliases.h>
#include <ETH.h>
#include <ETH_reg51.h>
#include <ETH_reg52.h>
#include <SSCR.h>
#include <SPI0_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

