/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <ETH0.h>
#include <SDCS.h>
#include <SDCS_aliases.h>
#include <SPI0.h>
#include <SPI0_SPI_UART.h>
#include <SPI0_PINS.h>
#include <SPI0_SPI_UART_PVT.h>
#include <SPI0_PVT.h>
#include <LED1.h>
#include <LED0.h>
#include <SPI0_ss0_m.h>
#include <SPI0_ss0_m_aliases.h>
#include <SPI0_mosi_m.h>
#include <SPI0_mosi_m_aliases.h>
#include <SPI0_miso_m.h>
#include <SPI0_miso_m_aliases.h>
#include <SPI0_sclk_m.h>
#include <SPI0_sclk_m_aliases.h>
#include <SPI0_ss1_m.h>
#include <SPI0_ss1_m_aliases.h>
#include <SPI0_SCBCLK.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

