# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\chuck.erhardt\Documents\GitHub\PSoC-W5100-Driver\freeSoCExplorer+ArduinoSheld_Example.cydsn\freeSoCExplorer+ArduinoSheld_Example.cyprj
# Date: Mon, 06 Jan 2014 21:55:02 GMT
#set_units -time ns
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 15.625 -waveform {0 7.8125} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 15.625 -waveform {0 7.8125} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {SPI0_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 3 5} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]


# Component constraints for C:\Users\chuck.erhardt\Documents\GitHub\PSoC-W5100-Driver\freeSoCExplorer+ArduinoSheld_Example.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\chuck.erhardt\Documents\GitHub\PSoC-W5100-Driver\freeSoCExplorer+ArduinoSheld_Example.cydsn\freeSoCExplorer+ArduinoSheld_Example.cyprj
# Date: Mon, 06 Jan 2014 21:54:52 GMT
