/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <MISO_1_aliases.h>
#include <MISO_1.h>
#include <MOSI_1_aliases.h>
#include <MOSI_1.h>
#include <SCLK_1_aliases.h>
#include <SCLK_1.h>
#include <SPI.h>
#include <SPI_PVT.h>
#include <SSCR.h>
#include <CSN_1_aliases.h>
#include <CSN_1.h>
#include <ETH.h>
#include <ETH_reg51.h>
#include <ETH_reg52.h>
#include <SPI_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

